<?php
/**
 * IndicatorsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Pago Facil
 *
 * API de Pago Fácil
 *
 * OpenAPI spec version: 2.1.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * IndicatorsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IndicatorsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation indicatorsRemittancesGet
     *
     * Obtiene los datos de los abonos (remittances) realizados en una fecha específica y los futuros, además del saldo disponible
     *
     * @param  \Swagger\Client\Model\IdUser $id_user ID del usuario a consultar (optional)
     * @param  \Swagger\Client\Model\IdTrx $id_trx ID de la transacción a consultar (optional)
     * @param  bool $available_balance Define si se desea obtener el saldo disponible del usuario (optional)
     * @param  \Swagger\Client\Model\\DateTime $remittance_by_date Fecha de la que se desea obtener información del abono (optional)
     * @param  bool $future_remittances Define si se desea obtener los abonos futuros (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ResponseBodyRemittances
     */
    public function indicatorsRemittancesGet($id_user = null, $id_trx = null, $available_balance = null, $remittance_by_date = null, $future_remittances = null)
    {
        list($response) = $this->indicatorsRemittancesGetWithHttpInfo($id_user, $id_trx, $available_balance, $remittance_by_date, $future_remittances);
        return $response;
    }

    /**
     * Operation indicatorsRemittancesGetWithHttpInfo
     *
     * Obtiene los datos de los abonos (remittances) realizados en una fecha específica y los futuros, además del saldo disponible
     *
     * @param  \Swagger\Client\Model\IdUser $id_user ID del usuario a consultar (optional)
     * @param  \Swagger\Client\Model\IdTrx $id_trx ID de la transacción a consultar (optional)
     * @param  bool $available_balance Define si se desea obtener el saldo disponible del usuario (optional)
     * @param  \Swagger\Client\Model\\DateTime $remittance_by_date Fecha de la que se desea obtener información del abono (optional)
     * @param  bool $future_remittances Define si se desea obtener los abonos futuros (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ResponseBodyRemittances, HTTP status code, HTTP response headers (array of strings)
     */
    public function indicatorsRemittancesGetWithHttpInfo($id_user = null, $id_trx = null, $available_balance = null, $remittance_by_date = null, $future_remittances = null)
    {
        $returnType = '\Swagger\Client\Model\ResponseBodyRemittances';
        $request = $this->indicatorsRemittancesGetRequest($id_user, $id_trx, $available_balance, $remittance_by_date, $future_remittances);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ResponseBodyRemittances',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse403',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse404',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation indicatorsRemittancesGetAsync
     *
     * Obtiene los datos de los abonos (remittances) realizados en una fecha específica y los futuros, además del saldo disponible
     *
     * @param  \Swagger\Client\Model\IdUser $id_user ID del usuario a consultar (optional)
     * @param  \Swagger\Client\Model\IdTrx $id_trx ID de la transacción a consultar (optional)
     * @param  bool $available_balance Define si se desea obtener el saldo disponible del usuario (optional)
     * @param  \Swagger\Client\Model\\DateTime $remittance_by_date Fecha de la que se desea obtener información del abono (optional)
     * @param  bool $future_remittances Define si se desea obtener los abonos futuros (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indicatorsRemittancesGetAsync($id_user = null, $id_trx = null, $available_balance = null, $remittance_by_date = null, $future_remittances = null)
    {
        return $this->indicatorsRemittancesGetAsyncWithHttpInfo($id_user, $id_trx, $available_balance, $remittance_by_date, $future_remittances)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation indicatorsRemittancesGetAsyncWithHttpInfo
     *
     * Obtiene los datos de los abonos (remittances) realizados en una fecha específica y los futuros, además del saldo disponible
     *
     * @param  \Swagger\Client\Model\IdUser $id_user ID del usuario a consultar (optional)
     * @param  \Swagger\Client\Model\IdTrx $id_trx ID de la transacción a consultar (optional)
     * @param  bool $available_balance Define si se desea obtener el saldo disponible del usuario (optional)
     * @param  \Swagger\Client\Model\\DateTime $remittance_by_date Fecha de la que se desea obtener información del abono (optional)
     * @param  bool $future_remittances Define si se desea obtener los abonos futuros (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function indicatorsRemittancesGetAsyncWithHttpInfo($id_user = null, $id_trx = null, $available_balance = null, $remittance_by_date = null, $future_remittances = null)
    {
        $returnType = '\Swagger\Client\Model\ResponseBodyRemittances';
        $request = $this->indicatorsRemittancesGetRequest($id_user, $id_trx, $available_balance, $remittance_by_date, $future_remittances);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'indicatorsRemittancesGet'
     *
     * @param  \Swagger\Client\Model\IdUser $id_user ID del usuario a consultar (optional)
     * @param  \Swagger\Client\Model\IdTrx $id_trx ID de la transacción a consultar (optional)
     * @param  bool $available_balance Define si se desea obtener el saldo disponible del usuario (optional)
     * @param  \Swagger\Client\Model\\DateTime $remittance_by_date Fecha de la que se desea obtener información del abono (optional)
     * @param  bool $future_remittances Define si se desea obtener los abonos futuros (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function indicatorsRemittancesGetRequest($id_user = null, $id_trx = null, $available_balance = null, $remittance_by_date = null, $future_remittances = null)
    {

        $resourcePath = '/indicators/remittances';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_user !== null) {
            $queryParams['idUser'] = ObjectSerializer::toQueryValue($id_user);
        }
        // query params
        if ($id_trx !== null) {
            $queryParams['idTrx'] = ObjectSerializer::toQueryValue($id_trx);
        }
        // query params
        if ($available_balance !== null) {
            $queryParams['availableBalance'] = ObjectSerializer::toQueryValue($available_balance);
        }
        // query params
        if ($remittance_by_date !== null) {
            $queryParams['remittanceByDate'] = ObjectSerializer::toQueryValue($remittance_by_date);
        }
        // query params
        if ($future_remittances !== null) {
            $queryParams['futureRemittances'] = ObjectSerializer::toQueryValue($future_remittances);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
