<?php
/**
 * NullificationType
 *
 * PHP version 5
 *
 * @category Class
 * @package  PSTPAGOFACIL\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Pago Facil
 *
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PSTPAGOFACIL\ApiClient\Model;
use \PSTPAGOFACIL\ApiClient\ObjectSerializer;

/**
 * NullificationType Class Doc Comment
 *
 * @category Class
 * @description Tipo de anulación
 * @package  PSTPAGOFACIL\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NullificationType
{
    /**
     * Possible values of this enum
     */
    const TOTAL = 'total';
    const PARCIAL = 'parcial';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TOTAL,
            self::PARCIAL,
        ];
    }
}


