<?php
/**
 * NullificationGetInner
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Pago Facil
 *
 * API de Pago Fácil
 *
 * OpenAPI spec version: 2.1.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * NullificationGetInner Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NullificationGetInner implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'nullification_get_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'verification_token' => '\Swagger\Client\Model\Uuid',
'monto_anulado' => '\Swagger\Client\Model\Amount',
'monto_descuento' => '\Swagger\Client\Model\Amount',
'date' => '\Swagger\Client\Model\\DateTime',
'type' => '\Swagger\Client\Model\NullificationType'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'verification_token' => null,
'monto_anulado' => null,
'monto_descuento' => null,
'date' => null,
'type' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'verification_token' => 'verificationToken',
'monto_anulado' => 'montoAnulado',
'monto_descuento' => 'montoDescuento',
'date' => 'date',
'type' => 'type'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'verification_token' => 'setVerificationToken',
'monto_anulado' => 'setMontoAnulado',
'monto_descuento' => 'setMontoDescuento',
'date' => 'setDate',
'type' => 'setType'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'verification_token' => 'getVerificationToken',
'monto_anulado' => 'getMontoAnulado',
'monto_descuento' => 'getMontoDescuento',
'date' => 'getDate',
'type' => 'getType'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['verification_token'] = isset($data['verification_token']) ? $data['verification_token'] : null;
        $this->container['monto_anulado'] = isset($data['monto_anulado']) ? $data['monto_anulado'] : null;
        $this->container['monto_descuento'] = isset($data['monto_descuento']) ? $data['monto_descuento'] : null;
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets verification_token
     *
     * @return \Swagger\Client\Model\Uuid
     */
    public function getVerificationToken()
    {
        return $this->container['verification_token'];
    }

    /**
     * Sets verification_token
     *
     * @param \Swagger\Client\Model\Uuid $verification_token verification_token
     *
     * @return $this
     */
    public function setVerificationToken($verification_token)
    {
        $this->container['verification_token'] = $verification_token;

        return $this;
    }

    /**
     * Gets monto_anulado
     *
     * @return \Swagger\Client\Model\Amount
     */
    public function getMontoAnulado()
    {
        return $this->container['monto_anulado'];
    }

    /**
     * Sets monto_anulado
     *
     * @param \Swagger\Client\Model\Amount $monto_anulado monto_anulado
     *
     * @return $this
     */
    public function setMontoAnulado($monto_anulado)
    {
        $this->container['monto_anulado'] = $monto_anulado;

        return $this;
    }

    /**
     * Gets monto_descuento
     *
     * @return \Swagger\Client\Model\Amount
     */
    public function getMontoDescuento()
    {
        return $this->container['monto_descuento'];
    }

    /**
     * Sets monto_descuento
     *
     * @param \Swagger\Client\Model\Amount $monto_descuento monto_descuento
     *
     * @return $this
     */
    public function setMontoDescuento($monto_descuento)
    {
        $this->container['monto_descuento'] = $monto_descuento;

        return $this;
    }

    /**
     * Gets date
     *
     * @return \Swagger\Client\Model\\DateTime
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \Swagger\Client\Model\\DateTime $date date
     *
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Swagger\Client\Model\NullificationType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Swagger\Client\Model\NullificationType $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
