<?php
/**
 * InlineResponse2005TypesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Pago Facil
 *
 * API de Pago Fácil
 *
 * OpenAPI spec version: 2.1.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2005TypesTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2005Types
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2005TypesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2005Types"
     */
    public function testInlineResponse2005Types()
    {
    }

    /**
     * Test attribute "codigo"
     */
    public function testPropertyCodigo()
    {
    }

    /**
     * Test attribute "nombre"
     */
    public function testPropertyNombre()
    {
    }

    /**
     * Test attribute "descripcion"
     */
    public function testPropertyDescripcion()
    {
    }

    /**
     * Test attribute "url_imagen"
     */
    public function testPropertyUrlImagen()
    {
    }
}
