<?php
/**
 * RequestBodyTrxTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Pago Facil
 *
 * API de Pago Fácil
 *
 * OpenAPI spec version: 2.1.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RequestBodyTrxTest Class Doc Comment
 *
 * @category    Class
 * @description RequestBodyTrx
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestBodyTrxTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestBodyTrx"
     */
    public function testRequestBodyTrx()
    {
    }

    /**
     * Test attribute "x_account_id"
     */
    public function testPropertyXAccountId()
    {
    }

    /**
     * Test attribute "x_amount"
     */
    public function testPropertyXAmount()
    {
    }

    /**
     * Test attribute "x_currency"
     */
    public function testPropertyXCurrency()
    {
    }

    /**
     * Test attribute "x_reference"
     */
    public function testPropertyXReference()
    {
    }

    /**
     * Test attribute "x_customer_email"
     */
    public function testPropertyXCustomerEmail()
    {
    }

    /**
     * Test attribute "x_url_complete"
     */
    public function testPropertyXUrlComplete()
    {
    }

    /**
     * Test attribute "x_url_callback"
     */
    public function testPropertyXUrlCallback()
    {
    }

    /**
     * Test attribute "x_url_cancel"
     */
    public function testPropertyXUrlCancel()
    {
    }

    /**
     * Test attribute "x_shop_country"
     */
    public function testPropertyXShopCountry()
    {
    }

    /**
     * Test attribute "x_session_id"
     */
    public function testPropertyXSessionId()
    {
    }

    /**
     * Test attribute "x_products"
     */
    public function testPropertyXProducts()
    {
    }

    /**
     * Test attribute "x_billing_details"
     */
    public function testPropertyXBillingDetails()
    {
    }

    /**
     * Test attribute "x_shippment"
     */
    public function testPropertyXShippment()
    {
    }

    /**
     * Test attribute "x_document"
     */
    public function testPropertyXDocument()
    {
    }

    /**
     * Test attribute "x_signature"
     */
    public function testPropertyXSignature()
    {
    }
}
