<?php
/**
 * ResponseBodyGetTrxDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Pago Facil
 *
 * API de Pago Fácil
 *
 * OpenAPI spec version: 2.1.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseBodyGetTrxDataTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseBodyGetTrxData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseBodyGetTrxDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseBodyGetTrxData"
     */
    public function testResponseBodyGetTrxData()
    {
    }

    /**
     * Test attribute "id_trx"
     */
    public function testPropertyIdTrx()
    {
    }

    /**
     * Test attribute "id_service"
     */
    public function testPropertyIdService()
    {
    }

    /**
     * Test attribute "order_id_tienda"
     */
    public function testPropertyOrderIdTienda()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {
    }

    /**
     * Test attribute "complete_url"
     */
    public function testPropertyCompleteUrl()
    {
    }

    /**
     * Test attribute "cancel_url"
     */
    public function testPropertyCancelUrl()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "browser_data"
     */
    public function testPropertyBrowserData()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "payment_type_code"
     */
    public function testPropertyPaymentTypeCode()
    {
    }

    /**
     * Test attribute "shares_number"
     */
    public function testPropertySharesNumber()
    {
    }

    /**
     * Test attribute "responce_code"
     */
    public function testPropertyResponceCode()
    {
    }

    /**
     * Test attribute "vci"
     */
    public function testPropertyVci()
    {
    }

    /**
     * Test attribute "abonos"
     */
    public function testPropertyAbonos()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
