<?php
/**
 * TrxsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Pago Facil
 *
 * API de Pago Fácil
 *
 * OpenAPI spec version: 2.1.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TrxsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TrxsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for trxsIdGet
     *
     * Obtiene la informacion de la transacción exitosa, asociada a un id.
     *
     */
    public function testTrxsIdGet()
    {
    }

    /**
     * Test case for trxsIdTrxNullificationGet
     *
     * .
     *
     */
    public function testTrxsIdTrxNullificationGet()
    {
    }

    /**
     * Test case for trxsIdTrxNullificationPost
     *
     * .
     *
     */
    public function testTrxsIdTrxNullificationPost()
    {
    }

    /**
     * Test case for trxsIdTrxNullificationStatusGet
     *
     * .
     *
     */
    public function testTrxsIdTrxNullificationStatusGet()
    {
    }

    /**
     * Test case for trxsPost
     *
     * .
     *
     */
    public function testTrxsPost()
    {
    }
}
