<?php
/**
 * TrxsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PSTPAGOFACIL\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Pago Facil
 *
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PSTPAGOFACIL\ApiClient;

use \PSTPAGOFACIL\ApiClient\Configuration;
use \PSTPAGOFACIL\ApiClient\ApiException;
use \PSTPAGOFACIL\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TrxsApiTest Class Doc Comment
 *
 * @category Class
 * @package  PSTPAGOFACIL\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrxsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for trxsIdGet
     *
     * Obtiene la informacion de la transacción exitosa, asociada a un id.
     *
     */
    public function testTrxsIdGet()
    {
    }

    /**
     * Test case for trxsIdTrxNullificationGet
     *
     * .
     *
     */
    public function testTrxsIdTrxNullificationGet()
    {
    }

    /**
     * Test case for trxsIdTrxNullificationPost
     *
     * .
     *
     */
    public function testTrxsIdTrxNullificationPost()
    {
    }

    /**
     * Test case for trxsIdTrxNullificationStatusGet
     *
     * .
     *
     */
    public function testTrxsIdTrxNullificationStatusGet()
    {
    }

    /**
     * Test case for trxsPost
     *
     * .
     *
     */
    public function testTrxsPost()
    {
    }
}
